#!/usr/bin/env bash
# Build + run tests/cel_lite_smoke.am — the CEL-lite lexer + Pratt
# parser + evaluator assertions. Same staging strategy as
# build-v3-validator-smoke.sh : rebuild the package archive, stage a
# dev tag in the amc cache, link the smoke binary against it.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RT="$HOME/.local/share/amalgame/runtime"
LIB="$HOME/.local/share/amalgame/lib/libamalgame.a"
AMC="$HOME/.local/bin/amc"

if [ ! -x "$AMC" ]; then
    echo "build-cel-lite-smoke: amc binary missing at $AMC" >&2
    exit 1
fi

echo "→ amc --lib facade.am"
"$AMC" --lib --quiet facade.am -o /tmp/Pollen-facade

echo "→ gcc -c /tmp/Pollen-facade.c"
gcc -O2 -I"$RT" -I./runtime \
    -Wno-int-conversion -Wno-incompatible-pointer-types \
    -c /tmp/Pollen-facade.c -o /tmp/Pollen-facade.o

mkdir -p build/linux-x86_64
ar rcs build/linux-x86_64/libamalgame-pkg-Pollen.a /tmp/Pollen-facade.o
PKGA="$ROOT/build/linux-x86_64/libamalgame-pkg-Pollen.a"

DEV_TAG="v0.2.0-dev"
DEV_SHA="local001"
DEV_DIR="$HOME/.amalgame/packages/github.com/amalgame-lang/amalgame-pollen/${DEV_TAG}_${DEV_SHA}"

rm -rf "$DEV_DIR"
mkdir -p "$DEV_DIR/build/linux-x86_64"
cp facade.am "$DEV_DIR/facade.am"
cp -r runtime "$DEV_DIR/runtime"
cp build/linux-x86_64/libamalgame-pkg-Pollen.a "$DEV_DIR/build/linux-x86_64/"

sed "s/^version           = \"[^\"]*\"/version           = \"0.2.0-dev\"/" \
    amalgame.toml > "$DEV_DIR/amalgame.toml"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cp tests/cel_lite_smoke.am "$WORK/cel_lite_smoke.am"

cat > "$WORK/amalgame.toml" <<TOML
[package]
name              = "cel-lite-smoke"
version           = "0.1.0"
required-amalgame = ">=0.8.52"

[dependencies]
amalgame-pollen = ">=0.2.0-dev"
TOML

cat > "$WORK/amalgame.lock" <<LOCK
# amalgame.lock — auto-generated by build-cel-lite-smoke.sh

[[package]]
name = "amalgame-pollen"
git  = "github.com/amalgame-lang/amalgame-pollen"
tag  = "${DEV_TAG}"
rev  = "${DEV_SHA}"
LOCK

echo "→ amc cel_lite_smoke.am"
( cd "$WORK" && "$AMC" --quiet cel_lite_smoke.am -o cel_lite_smoke >/dev/null )

echo "→ gcc link → tests/cel_lite_smoke"
gcc -O2 -I"$RT" -I"$DEV_DIR/runtime" \
    -Wno-int-conversion -Wno-incompatible-pointer-types \
    "$WORK/cel_lite_smoke.c" \
    -Wl,--start-group "$PKGA" "$LIB" -Wl,--end-group \
    -lgc -lm -lpthread \
    -o "$ROOT/tests/cel_lite_smoke"

echo "→ running"
echo
OUTPUT="$("$ROOT/tests/cel_lite_smoke")"
echo "$OUTPUT"
echo
if echo "$OUTPUT" | grep -q "^OK"; then
    exit 0
else
    exit 1
fi
