#!/usr/bin/env bash
# Build + run tests/v3_validator_smoke.am.
#
# The v3 validator is added in unreleased dev code that isn't yet in
# the package index, so this script :
#
#   1. Rebuilds libamalgame-pkg-Pollen.a from the local facade.am.
#   2. Materialises a synthetic dev package in the amc cache (named
#      v0.2.0-dev_local so `sort -V | tail -1` picks it ahead of the
#      released v0.1.x tags).
#   3. Spins up a tmp workspace with the matching amalgame.toml /
#      amalgame.lock pinning the dev tag, then `amc build`s the smoke
#      test against it.
#   4. Runs the resulting binary from the package root so the relative
#      `examples/...` paths in the smoke test resolve.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RT="$HOME/.local/share/amalgame/runtime"
LIB="$HOME/.local/share/amalgame/lib/libamalgame.a"
AMC="$HOME/.local/bin/amc"

if [ ! -x "$AMC" ]; then
    echo "build-v3-validator-smoke: amc binary missing at $AMC" >&2
    exit 1
fi

# ── 1. Package archive from the local facade.am ─────────────────────
echo "→ amc --lib facade.am"
"$AMC" --lib --quiet facade.am -o /tmp/Pollen-facade

echo "→ gcc -c /tmp/Pollen-facade.c"
gcc -O2 -I"$RT" -I./runtime \
    -Wno-int-conversion -Wno-incompatible-pointer-types \
    -c /tmp/Pollen-facade.c -o /tmp/Pollen-facade.o

mkdir -p build/linux-x86_64
ar rcs build/linux-x86_64/libamalgame-pkg-Pollen.a /tmp/Pollen-facade.o
PKGA="$ROOT/build/linux-x86_64/libamalgame-pkg-Pollen.a"
echo "  archive: $PKGA"

# ── 2. Dev package in the amc cache ─────────────────────────────────
DEV_TAG="v0.2.0-dev"
DEV_SHA="local001"
DEV_DIR="$HOME/.amalgame/packages/github.com/amalgame-lang/amalgame-pollen/${DEV_TAG}_${DEV_SHA}"

rm -rf "$DEV_DIR"
mkdir -p "$DEV_DIR/build/linux-x86_64"
cp facade.am "$DEV_DIR/facade.am"
cp -r runtime "$DEV_DIR/runtime"
cp build/linux-x86_64/libamalgame-pkg-Pollen.a "$DEV_DIR/build/linux-x86_64/"

# Patch the dev manifest's [package] version + amc-floor to keep
# precompile happy.
sed "s/^version           = \"[^\"]*\"/version           = \"0.2.0-dev\"/" \
    amalgame.toml > "$DEV_DIR/amalgame.toml"
echo "  cache:   $DEV_DIR"

# ── 3. Tmp workspace with toml + lock pointing at the dev tag ──────
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cp tests/v3_validator_smoke.am "$WORK/v3_validator_smoke.am"

cat > "$WORK/amalgame.toml" <<TOML
[package]
name              = "v3-validator-smoke"
version           = "0.1.0"
required-amalgame = ">=0.8.52"

[dependencies]
amalgame-pollen = ">=0.2.0-dev"
TOML

cat > "$WORK/amalgame.lock" <<LOCK
# amalgame.lock — auto-generated by build-v3-validator-smoke.sh

[[package]]
name = "amalgame-pollen"
git  = "github.com/amalgame-lang/amalgame-pollen"
tag  = "${DEV_TAG}"
rev  = "${DEV_SHA}"
LOCK

echo "→ amc v3_validator_smoke.am (in $WORK)"
( cd "$WORK" && "$AMC" --quiet v3_validator_smoke.am -o v3_validator_smoke >/dev/null )

echo "→ gcc link → tests/v3_validator_smoke"
gcc -O2 -I"$RT" -I"$DEV_DIR/runtime" \
    -Wno-int-conversion -Wno-incompatible-pointer-types \
    "$WORK/v3_validator_smoke.c" \
    -Wl,--start-group "$PKGA" "$LIB" -Wl,--end-group \
    -lgc -lm -lpthread \
    -o "$ROOT/tests/v3_validator_smoke"

# ── 4. Run from the package root so examples/... resolves ──────────
echo "→ running"
echo
OUTPUT="$("$ROOT/tests/v3_validator_smoke")"
echo "$OUTPUT"
echo
if echo "$OUTPUT" | grep -q "^OK"; then
    exit 0
else
    exit 1
fi
